### PR TITLE
added surajworld

### PR DESCRIPTION
**Pull request by SurajDatta**
Hi, I am doing the task: World Generation - Step 1: Make your own world generator ( MovingBlocks )
and have added a new world called "surajworld" and within that file, there is MountainProvider, SurajWorldGenerator, SurajWorldRasterizer, and SurafaceProvider. 

Hope you like it!

the world should contain a blank world with snow on top, grass directly below snow and dirt at the very bottom.

### CODE REVIEW

**Comment by mjuvekar7** [comment]
Looks good! I'm approving the task, but I'm holding off on merging this for one little change. Currently, your snow block spawn above a grass block. That looks a bit ugly. Try making it spawn _instead of_ the grass block

**Comment by mjuvekar7** [comment]
You could check this out if you want.
https://github.com/mjuvekar7/AlpineWorldGenerator

**Comment by SurajDatta** [comment]
Hi, I have added new houses and a frozen lake, Please have a look!

**Comment by mjuvekar7** [comment]
Please reduce the frequency of the houses spawning. There's too many houses!!

**Comment by SurajDatta** [comment]
Reduced the frequency of houses and added mountain Configs as 3rd mod

**Comment by SurajDatta** [comment]
I have added caves to my code

**Comment by PAndaContron** [comment]
Before this can be merged you should change the plugins to be regular world generator classes, since plugins have been causing lots of issues with this module.

**Comment by skaldarnar** [comment]
Thanks for the contribution, works out fine (the grass is floating one block in the air, though o.O)

I'm closing this it is an alteration of our [Terasology/TutorialWorldGeneration](https://github.com/Terasology/TutorialWorldGeneration).

**Pull request closed without merging**
